# Generated by Django 5.1.4 on 2025-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('Gd', 'Used Good'), ('Fr', 'Used Fair'), ('Ne', 'New'), ('Po', 'Used Poor'), ('Ex', 'Used Excellent')], default='Ex', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='books.genre'),
        ),
    ]
